#!/usr/bin/env node

var Twit = require('twit');
var fs = require('fs');
var Base64 = require('base64');

var twit = new Twit(require(__dirname + '/config.json'));

var avatars = fs.readdirSync(__dirname + '/avatars').filter(function(a) { return a[0] != '.'; });
var avatar = avatars[Math.floor(Math.random() * avatars.length)];
var image = Base64.encode(fs.readFileSync(__dirname + '/avatars/' + avatar));

twit.post('account/update_profile_image', { image: image }, function() {
	console.log(avatar);
});

// vim: set ft=javascript :
